name: "con_cache"

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: dev

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        elixir: ["1.14"]
        otp: ["25"]

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_

      - run: mix deps.get

      - run: mix deps.compile

      - run: mix format --check-formatted

      - run: mix deps.unlock --check-unused

      - run: mix dialyzer

      - run: mix docs

  test:
    runs-on: ${{ matrix.os }}
    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }}, OS ${{ matrix.os }}
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        elixir: ["1.14", "1.13", "1.12"]
        otp: ["25", "24", "23"]

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Restore cached deps
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_

      - run: mix deps.get

      - run: mix compile --warnings-as-errors

      - run: mix test
